//
// Author: Jim He
//
// Assignment: EE 271 Final Project: iWaaave Pro - Audio Signal Processing & Waveform Display
//
// Date Started: March 7, 2026
//
// Date Completed: March 7, 2026
//
// Description: This module implements the 256-point Cooley-Tukey (Radix-2) Decimation-in-Time (DIT) FFT Algorithm, using an iterative approach with a FSM.
//					
//

// FFT_256pt_engine.sv


// Message // This module supercedes the FFT_16pt_engine.sv module


// ============================================================
// FFT_256pt_engine.sv — 256-Point Radix-2 DIT FFT Engine
// ============================================================
// Algorithm: Cooley-Tukey Radix-2 DIT
// Stages: 8 (log2(256) = 8)
// Butterflies per stage: 128 (N/2)
// Arithmetic: Fixed-point Q1.14 (16-bit signed)
// Twiddle factors: Pre-computed in ROM, loaded from .hex file
//
// State machine flow:
//   IDLE → LOAD → STAGE1 → STAGE2 → ... → STAGE8 → DONE → IDLE
//
// Each STAGE iterates through 128 butterfly operations.
// ============================================================


module FFT_256pt_engine (clk, reset, start, X_in, X_re, X_im, done_signal);
	input  logic        clk;
	input  logic        reset;
	input  logic        start;
	input  logic signed [15:0] X_in [0:255];
	output logic signed [15:0] X_re [0:255];
	output logic signed [15:0] X_im [0:255];
	output logic        done_signal;
	

	
	// -------------------------------------------------------
	// State Machine
	// -------------------------------------------------------
	typedef enum logic [3:0] {
			S_IDLE   = 4'd0,
			S_LOAD   = 4'd1,
			S_STAGE1 = 4'd2,
			S_STAGE2 = 4'd3,
			S_STAGE3 = 4'd4,
			S_STAGE4 = 4'd5,
			S_STAGE5 = 4'd6,
			S_STAGE6 = 4'd7,
			S_STAGE7 = 4'd8,
			S_STAGE8 = 4'd9,
			S_DONE   = 4'd10
	} state_t;
	
	state_t present_state, next_state;


	
	// -------------------------------------------------------
	// Working data arrays (real and imaginary) — use block RAM
	// -------------------------------------------------------
	logic signed [15:0] data_re [0:255];
	logic signed [15:0] data_im [0:255];
	
	
	// -------------------------------------------------------
	// Butterfly counter: 0 to 127 (128 butterflies per stage)
	// -------------------------------------------------------
	logic [6:0] bfly_cnt;
	
	
	
	// -------------------------------------------------------
	// Twiddle Factor ROM
	// -------------------------------------------------------
	// W_256^k = cos(2πk/256) - j·sin(2πk/256)
	// We need k = 0 to 127 (N/2 - 1)
	// Stored in Q1.14: value = round(trig_value * 16384)
	// ROM initialized from .hex files generated by Python script
	// -------------------------------------------------------
	
	logic signed [15:0] tw_re [0:127];
	logic signed [15:0] tw_im [0:127];

//	// Use python script - generate_twiddle_hex.py
//	initial 
//	begin
//		$readmemh("twiddle_re_256.hex", tw_re);
//		$readmemh("twiddle_im_256.hex", tw_im);
//	end

	// ? // How do we run the python script first to generate it?
	
	// Alternatively, we can hard-code them ourselves
    // k=0:   cos=1.000000, sin=0.000000
    assign tw_re[  0] =  16'sd16384;    assign tw_im[  0] =  16'sd0;
    // k=1:   cos=0.999699, sin=0.024541
    assign tw_re[  1] =  16'sd16379;    assign tw_im[  1] = -16'sd402;
    // k=2:   cos=0.998795, sin=0.049068
    assign tw_re[  2] =  16'sd16364;    assign tw_im[  2] = -16'sd804;
    // k=3:   cos=0.997290, sin=0.073565
    assign tw_re[  3] =  16'sd16340;    assign tw_im[  3] = -16'sd1205;
    // k=4:   cos=0.995185, sin=0.098017
    assign tw_re[  4] =  16'sd16305;    assign tw_im[  4] = -16'sd1606;
    // k=5:   cos=0.992480, sin=0.122411
    assign tw_re[  5] =  16'sd16261;    assign tw_im[  5] = -16'sd2006;
    // k=6:   cos=0.989177, sin=0.146730
    assign tw_re[  6] =  16'sd16207;    assign tw_im[  6] = -16'sd2404;
    // k=7:   cos=0.985278, sin=0.170962
    assign tw_re[  7] =  16'sd16143;    assign tw_im[  7] = -16'sd2801;
    // k=8:   cos=0.980785, sin=0.195090
    assign tw_re[  8] =  16'sd16069;    assign tw_im[  8] = -16'sd3196;
    // k=9:   cos=0.975702, sin=0.219101
    assign tw_re[  9] =  16'sd15986;    assign tw_im[  9] = -16'sd3590;
    // k=10:  cos=0.970031, sin=0.242980
    assign tw_re[ 10] =  16'sd15893;    assign tw_im[ 10] = -16'sd3981;
    // k=11:  cos=0.963776, sin=0.266713
    assign tw_re[ 11] =  16'sd15790;    assign tw_im[ 11] = -16'sd4370;
    // k=12:  cos=0.956940, sin=0.290285
    assign tw_re[ 12] =  16'sd15679;    assign tw_im[ 12] = -16'sd4756;
    // k=13:  cos=0.949528, sin=0.313682
    assign tw_re[ 13] =  16'sd15557;    assign tw_im[ 13] = -16'sd5139;
    // k=14:  cos=0.941544, sin=0.336890
    assign tw_re[ 14] =  16'sd15426;    assign tw_im[ 14] = -16'sd5520;
    // k=15:  cos=0.932993, sin=0.359895
    assign tw_re[ 15] =  16'sd15286;    assign tw_im[ 15] = -16'sd5897;
    // k=16:  cos=0.923880, sin=0.382683
    assign tw_re[ 16] =  16'sd15137;    assign tw_im[ 16] = -16'sd6270;
    // k=17:  cos=0.914210, sin=0.405241
    assign tw_re[ 17] =  16'sd14978;    assign tw_im[ 17] = -16'sd6639;
    // k=18:  cos=0.903989, sin=0.427555
    assign tw_re[ 18] =  16'sd14811;    assign tw_im[ 18] = -16'sd7005;
    // k=19:  cos=0.893224, sin=0.449611
    assign tw_re[ 19] =  16'sd14635;    assign tw_im[ 19] = -16'sd7366;
    // k=20:  cos=0.881921, sin=0.471397
    assign tw_re[ 20] =  16'sd14449;    assign tw_im[ 20] = -16'sd7723;
    // k=21:  cos=0.870087, sin=0.492898
    assign tw_re[ 21] =  16'sd14255;    assign tw_im[ 21] = -16'sd8076;
    // k=22:  cos=0.857729, sin=0.514103
    assign tw_re[ 22] =  16'sd14053;    assign tw_im[ 22] = -16'sd8423;
    // k=23:  cos=0.844854, sin=0.534998
    assign tw_re[ 23] =  16'sd13842;    assign tw_im[ 23] = -16'sd8765;
    // k=24:  cos=0.831470, sin=0.555570
    assign tw_re[ 24] =  16'sd13623;    assign tw_im[ 24] = -16'sd9102;
    // k=25:  cos=0.817585, sin=0.575808
    assign tw_re[ 25] =  16'sd13395;    assign tw_im[ 25] = -16'sd9434;
    // k=26:  cos=0.803208, sin=0.595699
    assign tw_re[ 26] =  16'sd13160;    assign tw_im[ 26] = -16'sd9760;
    // k=27:  cos=0.788346, sin=0.615232
    assign tw_re[ 27] =  16'sd12916;    assign tw_im[ 27] = -16'sd10080;
    // k=28:  cos=0.773010, sin=0.634393
    assign tw_re[ 28] =  16'sd12665;    assign tw_im[ 28] = -16'sd10394;
    // k=29:  cos=0.757209, sin=0.653173
    assign tw_re[ 29] =  16'sd12406;    assign tw_im[ 29] = -16'sd10702;
    // k=30:  cos=0.740951, sin=0.671559
    assign tw_re[ 30] =  16'sd12140;    assign tw_im[ 30] = -16'sd11003;
    // k=31:  cos=0.724247, sin=0.689541
    assign tw_re[ 31] =  16'sd11866;    assign tw_im[ 31] = -16'sd11297;
    // k=32:  cos=0.707107, sin=0.707107
    assign tw_re[ 32] =  16'sd11585;    assign tw_im[ 32] = -16'sd11585;
    // k=33:  cos=0.689541, sin=0.724247
    assign tw_re[ 33] =  16'sd11297;    assign tw_im[ 33] = -16'sd11866;
    // k=34:  cos=0.671559, sin=0.740951
    assign tw_re[ 34] =  16'sd11003;    assign tw_im[ 34] = -16'sd12140;
    // k=35:  cos=0.653173, sin=0.757209
    assign tw_re[ 35] =  16'sd10702;    assign tw_im[ 35] = -16'sd12406;
    // k=36:  cos=0.634393, sin=0.773010
    assign tw_re[ 36] =  16'sd10394;    assign tw_im[ 36] = -16'sd12665;
    // k=37:  cos=0.615232, sin=0.788346
    assign tw_re[ 37] =  16'sd10080;    assign tw_im[ 37] = -16'sd12916;
    // k=38:  cos=0.595699, sin=0.803208
    assign tw_re[ 38] =  16'sd9760;     assign tw_im[ 38] = -16'sd13160;
    // k=39:  cos=0.575808, sin=0.817585
    assign tw_re[ 39] =  16'sd9434;     assign tw_im[ 39] = -16'sd13395;
    // k=40:  cos=0.555570, sin=0.831470
    assign tw_re[ 40] =  16'sd9102;     assign tw_im[ 40] = -16'sd13623;
    // k=41:  cos=0.534998, sin=0.844854
    assign tw_re[ 41] =  16'sd8765;     assign tw_im[ 41] = -16'sd13842;
    // k=42:  cos=0.514103, sin=0.857729
    assign tw_re[ 42] =  16'sd8423;     assign tw_im[ 42] = -16'sd14053;
    // k=43:  cos=0.492898, sin=0.870087
    assign tw_re[ 43] =  16'sd8076;     assign tw_im[ 43] = -16'sd14255;
    // k=44:  cos=0.471397, sin=0.881921
    assign tw_re[ 44] =  16'sd7723;     assign tw_im[ 44] = -16'sd14449;
    // k=45:  cos=0.449611, sin=0.893224
    assign tw_re[ 45] =  16'sd7366;     assign tw_im[ 45] = -16'sd14635;
    // k=46:  cos=0.427555, sin=0.903989
    assign tw_re[ 46] =  16'sd7005;     assign tw_im[ 46] = -16'sd14811;
    // k=47:  cos=0.405241, sin=0.914210
    assign tw_re[ 47] =  16'sd6639;     assign tw_im[ 47] = -16'sd14978;
    // k=48:  cos=0.382683, sin=0.923880
    assign tw_re[ 48] =  16'sd6270;     assign tw_im[ 48] = -16'sd15137;
    // k=49:  cos=0.359895, sin=0.932993
    assign tw_re[ 49] =  16'sd5897;     assign tw_im[ 49] = -16'sd15286;
    // k=50:  cos=0.336890, sin=0.941544
    assign tw_re[ 50] =  16'sd5520;     assign tw_im[ 50] = -16'sd15426;
    // k=51:  cos=0.313682, sin=0.949528
    assign tw_re[ 51] =  16'sd5139;     assign tw_im[ 51] = -16'sd15557;
    // k=52:  cos=0.290285, sin=0.956940
    assign tw_re[ 52] =  16'sd4756;     assign tw_im[ 52] = -16'sd15679;
    // k=53:  cos=0.266713, sin=0.963776
    assign tw_re[ 53] =  16'sd4370;     assign tw_im[ 53] = -16'sd15790;
    // k=54:  cos=0.242980, sin=0.970031
    assign tw_re[ 54] =  16'sd3981;     assign tw_im[ 54] = -16'sd15893;
    // k=55:  cos=0.219101, sin=0.975702
    assign tw_re[ 55] =  16'sd3590;     assign tw_im[ 55] = -16'sd15986;
    // k=56:  cos=0.195090, sin=0.980785
    assign tw_re[ 56] =  16'sd3196;     assign tw_im[ 56] = -16'sd16069;
    // k=57:  cos=0.170962, sin=0.985278
    assign tw_re[ 57] =  16'sd2801;     assign tw_im[ 57] = -16'sd16143;
    // k=58:  cos=0.146730, sin=0.989177
    assign tw_re[ 58] =  16'sd2404;     assign tw_im[ 58] = -16'sd16207;
    // k=59:  cos=0.122411, sin=0.992480
    assign tw_re[ 59] =  16'sd2006;     assign tw_im[ 59] = -16'sd16261;
    // k=60:  cos=0.098017, sin=0.995185
    assign tw_re[ 60] =  16'sd1606;     assign tw_im[ 60] = -16'sd16305;
    // k=61:  cos=0.073565, sin=0.997290
    assign tw_re[ 61] =  16'sd1205;     assign tw_im[ 61] = -16'sd16340;
    // k=62:  cos=0.049068, sin=0.998795
    assign tw_re[ 62] =  16'sd804;      assign tw_im[ 62] = -16'sd16364;
    // k=63:  cos=0.024541, sin=0.999699
    assign tw_re[ 63] =  16'sd402;      assign tw_im[ 63] = -16'sd16379;
    // k=64:  cos=0.000000, sin=1.000000
    assign tw_re[ 64] =  16'sd0;        assign tw_im[ 64] = -16'sd16384;
    // k=65:  cos=-0.024541, sin=0.999699
    assign tw_re[ 65] = -16'sd402;      assign tw_im[ 65] = -16'sd16379;
    // k=66:  cos=-0.049068, sin=0.998795
    assign tw_re[ 66] = -16'sd804;      assign tw_im[ 66] = -16'sd16364;
    // k=67:  cos=-0.073565, sin=0.997290
    assign tw_re[ 67] = -16'sd1205;     assign tw_im[ 67] = -16'sd16340;
    // k=68:  cos=-0.098017, sin=0.995185
    assign tw_re[ 68] = -16'sd1606;     assign tw_im[ 68] = -16'sd16305;
    // k=69:  cos=-0.122411, sin=0.992480
    assign tw_re[ 69] = -16'sd2006;     assign tw_im[ 69] = -16'sd16261;
    // k=70:  cos=-0.146730, sin=0.989177
    assign tw_re[ 70] = -16'sd2404;     assign tw_im[ 70] = -16'sd16207;
    // k=71:  cos=-0.170962, sin=0.985278
    assign tw_re[ 71] = -16'sd2801;     assign tw_im[ 71] = -16'sd16143;
    // k=72:  cos=-0.195090, sin=0.980785
    assign tw_re[ 72] = -16'sd3196;     assign tw_im[ 72] = -16'sd16069;
    // k=73:  cos=-0.219101, sin=0.975702
    assign tw_re[ 73] = -16'sd3590;     assign tw_im[ 73] = -16'sd15986;
    // k=74:  cos=-0.242980, sin=0.970031
    assign tw_re[ 74] = -16'sd3981;     assign tw_im[ 74] = -16'sd15893;
    // k=75:  cos=-0.266713, sin=0.963776
    assign tw_re[ 75] = -16'sd4370;     assign tw_im[ 75] = -16'sd15790;
    // k=76:  cos=-0.290285, sin=0.956940
    assign tw_re[ 76] = -16'sd4756;     assign tw_im[ 76] = -16'sd15679;
    // k=77:  cos=-0.313682, sin=0.949528
    assign tw_re[ 77] = -16'sd5139;     assign tw_im[ 77] = -16'sd15557;
    // k=78:  cos=-0.336890, sin=0.941544
    assign tw_re[ 78] = -16'sd5520;     assign tw_im[ 78] = -16'sd15426;
    // k=79:  cos=-0.359895, sin=0.932993
    assign tw_re[ 79] = -16'sd5897;     assign tw_im[ 79] = -16'sd15286;
    // k=80:  cos=-0.382683, sin=0.923880
    assign tw_re[ 80] = -16'sd6270;     assign tw_im[ 80] = -16'sd15137;
    // k=81:  cos=-0.405241, sin=0.914210
    assign tw_re[ 81] = -16'sd6639;     assign tw_im[ 81] = -16'sd14978;
    // k=82:  cos=-0.427555, sin=0.903989
    assign tw_re[ 82] = -16'sd7005;     assign tw_im[ 82] = -16'sd14811;
    // k=83:  cos=-0.449611, sin=0.893224
    assign tw_re[ 83] = -16'sd7366;     assign tw_im[ 83] = -16'sd14635;
    // k=84:  cos=-0.471397, sin=0.881921
    assign tw_re[ 84] = -16'sd7723;     assign tw_im[ 84] = -16'sd14449;
    // k=85:  cos=-0.492898, sin=0.870087
    assign tw_re[ 85] = -16'sd8076;     assign tw_im[ 85] = -16'sd14255;
    // k=86:  cos=-0.514103, sin=0.857729
    assign tw_re[ 86] = -16'sd8423;     assign tw_im[ 86] = -16'sd14053;
    // k=87:  cos=-0.534998, sin=0.844854
    assign tw_re[ 87] = -16'sd8765;     assign tw_im[ 87] = -16'sd13842;
    // k=88:  cos=-0.555570, sin=0.831470
    assign tw_re[ 88] = -16'sd9102;     assign tw_im[ 88] = -16'sd13623;
    // k=89:  cos=-0.575808, sin=0.817585
    assign tw_re[ 89] = -16'sd9434;     assign tw_im[ 89] = -16'sd13395;
    // k=90:  cos=-0.595699, sin=0.803208
    assign tw_re[ 90] = -16'sd9760;     assign tw_im[ 90] = -16'sd13160;
    // k=91:  cos=-0.615232, sin=0.788346
    assign tw_re[ 91] = -16'sd10080;    assign tw_im[ 91] = -16'sd12916;
    // k=92:  cos=-0.634393, sin=0.773010
    assign tw_re[ 92] = -16'sd10394;    assign tw_im[ 92] = -16'sd12665;
    // k=93:  cos=-0.653173, sin=0.757209
    assign tw_re[ 93] = -16'sd10702;    assign tw_im[ 93] = -16'sd12406;
    // k=94:  cos=-0.671559, sin=0.740951
    assign tw_re[ 94] = -16'sd11003;    assign tw_im[ 94] = -16'sd12140;
    // k=95:  cos=-0.689541, sin=0.724247
    assign tw_re[ 95] = -16'sd11297;    assign tw_im[ 95] = -16'sd11866;
    // k=96:  cos=-0.707107, sin=0.707107
    assign tw_re[ 96] = -16'sd11585;    assign tw_im[ 96] = -16'sd11585;
    // k=97:  cos=-0.724247, sin=0.689541
    assign tw_re[ 97] = -16'sd11866;    assign tw_im[ 97] = -16'sd11297;
    // k=98:  cos=-0.740951, sin=0.671559
    assign tw_re[ 98] = -16'sd12140;    assign tw_im[ 98] = -16'sd11003;
    // k=99:  cos=-0.757209, sin=0.653173
    assign tw_re[ 99] = -16'sd12406;    assign tw_im[ 99] = -16'sd10702;
    // k=100: cos=-0.773010, sin=0.634393
    assign tw_re[100] = -16'sd12665;    assign tw_im[100] = -16'sd10394;
    // k=101: cos=-0.788346, sin=0.615232
    assign tw_re[101] = -16'sd12916;    assign tw_im[101] = -16'sd10080;
    // k=102: cos=-0.803208, sin=0.595699
    assign tw_re[102] = -16'sd13160;    assign tw_im[102] = -16'sd9760;
    // k=103: cos=-0.817585, sin=0.575808
    assign tw_re[103] = -16'sd13395;    assign tw_im[103] = -16'sd9434;
    // k=104: cos=-0.831470, sin=0.555570
    assign tw_re[104] = -16'sd13623;    assign tw_im[104] = -16'sd9102;
    // k=105: cos=-0.844854, sin=0.534998
    assign tw_re[105] = -16'sd13842;    assign tw_im[105] = -16'sd8765;
    // k=106: cos=-0.857729, sin=0.514103
    assign tw_re[106] = -16'sd14053;    assign tw_im[106] = -16'sd8423;
    // k=107: cos=-0.870087, sin=0.492898
    assign tw_re[107] = -16'sd14255;    assign tw_im[107] = -16'sd8076;
    // k=108: cos=-0.881921, sin=0.471397
    assign tw_re[108] = -16'sd14449;    assign tw_im[108] = -16'sd7723;
    // k=109: cos=-0.893224, sin=0.449611
    assign tw_re[109] = -16'sd14635;    assign tw_im[109] = -16'sd7366;
    // k=110: cos=-0.903989, sin=0.427555
    assign tw_re[110] = -16'sd14811;    assign tw_im[110] = -16'sd7005;
    // k=111: cos=-0.914210, sin=0.405241
    assign tw_re[111] = -16'sd14978;    assign tw_im[111] = -16'sd6639;
    // k=112: cos=-0.923880, sin=0.382683
    assign tw_re[112] = -16'sd15137;    assign tw_im[112] = -16'sd6270;
    // k=113: cos=-0.932993, sin=0.359895
    assign tw_re[113] = -16'sd15286;    assign tw_im[113] = -16'sd5897;
    // k=114: cos=-0.941544, sin=0.336890
    assign tw_re[114] = -16'sd15426;    assign tw_im[114] = -16'sd5520;
    // k=115: cos=-0.949528, sin=0.313682
    assign tw_re[115] = -16'sd15557;    assign tw_im[115] = -16'sd5139;
    // k=116: cos=-0.956940, sin=0.290285
    assign tw_re[116] = -16'sd15679;    assign tw_im[116] = -16'sd4756;
    // k=117: cos=-0.963776, sin=0.266713
    assign tw_re[117] = -16'sd15790;    assign tw_im[117] = -16'sd4370;
    // k=118: cos=-0.970031, sin=0.242980
    assign tw_re[118] = -16'sd15893;    assign tw_im[118] = -16'sd3981;
    // k=119: cos=-0.975702, sin=0.219101
    assign tw_re[119] = -16'sd15986;    assign tw_im[119] = -16'sd3590;
    // k=120: cos=-0.980785, sin=0.195090
    assign tw_re[120] = -16'sd16069;    assign tw_im[120] = -16'sd3196;
    // k=121: cos=-0.985278, sin=0.170962
    assign tw_re[121] = -16'sd16143;    assign tw_im[121] = -16'sd2801;
    // k=122: cos=-0.989177, sin=0.146730
    assign tw_re[122] = -16'sd16207;    assign tw_im[122] = -16'sd2404;
    // k=123: cos=-0.992480, sin=0.122411
    assign tw_re[123] = -16'sd16261;    assign tw_im[123] = -16'sd2006;
    // k=124: cos=-0.995185, sin=0.098017
    assign tw_re[124] = -16'sd16305;    assign tw_im[124] = -16'sd1606;
    // k=125: cos=-0.997290, sin=0.073565
    assign tw_re[125] = -16'sd16340;    assign tw_im[125] = -16'sd1205;
    // k=126: cos=-0.998795, sin=0.049068
    assign tw_re[126] = -16'sd16364;    assign tw_im[126] = -16'sd804;
    // k=127: cos=-0.999699, sin=0.024541
    assign tw_re[127] = -16'sd16379;    assign tw_im[127] = -16'sd402;

	
	
	
	// -------------------------------------------------------
	// Bit-Reversal Function (8-bit for 256-point)
	// -------------------------------------------------------
	function automatic [7:0] bit_reverse_8(input [7:0] idx);
		bit_reverse_8 = {idx[0], idx[1], idx[2], idx[3], idx[4], idx[5], idx[6], idx[7]};
   endfunction

	
	
	// -------------------------------------------------------
	// Stage number (1-8) derived from state for index calc
	// -------------------------------------------------------
	logic [3:0] stage_num;

	always_comb 
	begin
		case (present_state)
			S_STAGE1: stage_num = 4'd1;
			S_STAGE2: stage_num = 4'd2;
			S_STAGE3: stage_num = 4'd3;
			S_STAGE4: stage_num = 4'd4;
			S_STAGE5: stage_num = 4'd5;
			S_STAGE6: stage_num = 4'd6;
			S_STAGE7: stage_num = 4'd7;
			S_STAGE8: stage_num = 4'd8;
			default:  stage_num = 4'd0;
		endcase
	end


	
	// -------------------------------------------------------
	// Butterfly Index Calculation (generalized)
	// -------------------------------------------------------
	// For stage s (1-8), butterfly index b (0-127):
	//   half       = 2^(s-1)
	//   block_size = 2^s
	//   block_num  = b / half
	//   bfly_in_blk = b % half
	//   top_idx    = block_num * block_size + bfly_in_blk
	//   bot_idx    = top_idx + half
	//   tw_idx     = bfly_in_blk * (128 / half)
	//              = bfly_in_blk << (8 - s)
	// -------------------------------------------------------

	logic [7:0] top_idx, bot_idx;
	logic [6:0] tw_idx;

	// Intermediate values for index computation
	logic [7:0] half;
	logic [7:0] block_size;
	logic [7:0] block_num;
	logic [7:0] bfly_in_blk;

	always_comb 
	begin
		top_idx = 8'd0;
		bot_idx = 8'd0;
		tw_idx  = 7'd0;
		half         = 8'd0;
		block_size   = 8'd0;
		block_num    = 8'd0;
		bfly_in_blk  = 8'd0;

		if (stage_num >= 4'd1 && stage_num <= 4'd8) 
		begin
				// half = 1 << (stage_num - 1)
            half = 8'd1 << (stage_num - 4'd1);
            // block_size = 1 << stage_num
            block_size = 8'd1 << stage_num;
				
            // block_num = bfly_cnt / half
            // bfly_in_blk = bfly_cnt % half
            // Since half is always a power of 2, we can use bit masking:
            //   block_num = bfly_cnt >> (stage_num - 1)
            //   bfly_in_blk = bfly_cnt & (half - 1)
            block_num   = {1'b0, bfly_cnt} >> (stage_num - 4'd1);
            bfly_in_blk = {1'b0, bfly_cnt} & (half - 8'd1);

            top_idx = block_num * block_size + bfly_in_blk;
            bot_idx = top_idx + half;

            // tw_idx = bfly_in_blk * (128 / half) = bfly_in_blk << (8 - stage_num)
            // But we cap at 127
            tw_idx = (bfly_in_blk << (4'd8 - stage_num));
		end
	end


	
	// -------------------------------------------------------
	// Butterfly Computation (combinational)
	// -------------------------------------------------------
	logic signed [15:0] a_re, a_im, b_re, b_im;
	logic signed [15:0] w_re, w_im;
	logic signed [31:0] prod1, prod2, prod3, prod4;
	logic signed [31:0] t_re_full, t_im_full;
	logic signed [15:0] t_re, t_im;
	logic signed [16:0] sum_re, sum_im, diff_re, diff_im;  // 17-bit for overflow detection
	logic signed [15:0] a_out_re, a_out_im, b_out_re, b_out_im;

	always_comb 
	begin
		// Read inputs
		a_re = data_re[top_idx];
		a_im = data_im[top_idx];
		b_re = data_re[bot_idx];
		b_im = data_im[bot_idx];
		w_re = tw_re[tw_idx];
		w_im = tw_im[tw_idx];

		// Complex multiply: t = b * w
		// (b_re + j*b_im) * (w_re + j*w_im)
		// = (b_re*w_re - b_im*w_im) + j*(b_re*w_im + b_im*w_re)
		prod1 = b_re * w_re;   // Q1.14 * Q1.14 = Q2.28
		prod2 = b_im * w_im;
		prod3 = b_re * w_im;
		prod4 = b_im * w_re;

		t_re_full = (prod1 - prod2) >>> 14;  // Back to Q1.14
		t_im_full = (prod3 + prod4) >>> 14;

		// Saturate to 16-bit signed range to prevent overflow
		if (t_re_full > 32'sd32767)
			t_re = 16'sd32767;
		else if (t_re_full < -32'sd32768)
			t_re = -16'sd32768;
		else
			t_re = t_re_full[15:0];

		if (t_im_full > 32'sd32767)
			t_im = 16'sd32767;
		else if (t_im_full < -32'sd32768)
			t_im = -16'sd32768;
		else
			t_im = t_im_full[15:0];

		// Butterfly: add and subtract with saturation
		sum_re  = {a_re[15], a_re} + {t_re[15], t_re};   // sign-extend to 17 bits
		sum_im  = {a_im[15], a_im} + {t_im[15], t_im};
		diff_re = {a_re[15], a_re} - {t_re[15], t_re};
		diff_im = {a_im[15], a_im} - {t_im[15], t_im};
		
		// Saturate back to 16-bit
		a_out_re = (sum_re > 17'sd32767) ? 16'sd32767 : (sum_re < -17'sd32768) ? -16'sd32768 : sum_re[15:0];
		a_out_im = (sum_im > 17'sd32767) ? 16'sd32767 : (sum_im < -17'sd32768) ? -16'sd32768 : sum_im[15:0];
      b_out_re = (diff_re > 17'sd32767) ? 16'sd32767 : (diff_re < -17'sd32768) ? -16'sd32768 : diff_re[15:0];
		b_out_im = (diff_im > 17'sd32767) ? 16'sd32767 : (diff_im < -17'sd32768) ? -16'sd32768 : diff_im[15:0];
		
	end // END OF always_comb


	
	// -------------------------------------------------------
	// Load counter for bit-reversed loading
	// -------------------------------------------------------
	logic [7:0] load_cnt;
	logic load_done;

	

	// -------------------------------------------------------
	// Main State Machine & Data Path
	// -------------------------------------------------------
	always_ff @ (posedge clk) 
	begin
		if (reset) 
		begin
			present_state <= S_IDLE;
			done_signal   <= '0;
			bfly_cnt      <= '0;
			load_cnt      <= '0;
			load_done     <= '0;

			for (int i = 0; i < 256; i++) 
			begin
				data_re[i] <= 16'sd0;
				data_im[i] <= 16'sd0;
				X_re[i]    <= 16'sd0;
				X_im[i]    <= 16'sd0;
			end
		end

		else 
		begin
			done_signal <= '0;  // default: done is a single-cycle pulse

			case (present_state)
	
				S_IDLE: 
				begin
					if (start) 
					begin
						present_state <= S_LOAD;
						load_cnt      <= 8'd0;
						load_done     <= '0;
					end
				end

				
				S_LOAD: 
				begin
					// Load with bit-reversal, one sample per clock
					// This avoids the huge multiplexer of loading all 256
					// in one cycle (which the old 16-point version did)
					data_re[bit_reverse_8(load_cnt)] <= X_in[load_cnt];
					data_im[bit_reverse_8(load_cnt)] <= 16'sd0;

					if (load_cnt == 8'd255) 
					begin
						present_state <= S_STAGE1;
						bfly_cnt      <= 7'd0;
					end
					
					else 
					begin
						load_cnt <= load_cnt + 8'd1;
               end
				end

				
				S_STAGE1, S_STAGE2, S_STAGE3, S_STAGE4, S_STAGE5, S_STAGE6, S_STAGE7, S_STAGE8: 
				begin
					// Perform butterfly operation
					data_re[top_idx] <= a_out_re;
					data_im[top_idx] <= a_out_im;
					data_re[bot_idx] <= b_out_re;
					data_im[bot_idx] <= b_out_im;

					if (bfly_cnt == 7'd127) 
					begin
						// All 128 butterflies in this stage done
						bfly_cnt <= 7'd0;
						case (present_state)
							S_STAGE1: present_state <= S_STAGE2;
							S_STAGE2: present_state <= S_STAGE3;
							S_STAGE3: present_state <= S_STAGE4;
							S_STAGE4: present_state <= S_STAGE5;
							S_STAGE5: present_state <= S_STAGE6;
							S_STAGE6: present_state <= S_STAGE7;
							S_STAGE7: present_state <= S_STAGE8;
							S_STAGE8: present_state <= S_DONE;
							default:  present_state <= S_DONE;
						endcase
					end
               
					else 
					begin
						bfly_cnt <= bfly_cnt + 7'd1;
					end
				end // END OF S_STATE states block

				
				S_DONE: 
				begin
					// Copy results to output
					for (int i = 0; i < 256; i++) 
					begin
						X_re[i] <= data_re[i];
						X_im[i] <= data_im[i];
					end
						done_signal   <= 1'b1;
						present_state <= S_IDLE;
				end

				
				default: present_state <= S_IDLE;

			endcase
			
		end // END OF else block
		
	end // END OF always_ff (FSM State FFs)
	

endmodule